fontsDir: .local/share/fonts

terminalFont:
  fileName: 
    regular: Caskaydia Cove Nerd Font Complete Mono Regular.otf
    bold: Caskaydia Cove Nerd Font Complete Mono Bold.otf
    light: Caskaydia Cove Nerd Font Complete Mono Light.otf
  name: Caskaydia Cove Nerd Font Mono
  family: Caskaydia Cove
  
  wallpaper: /usr/share/backgrounds/arcolinux/arco-login.jpg
